# Site
title: Piotr Prucia
description: Moblie Software Developer | Cyclist
url: https://prucia.pl
#url: http://localhost:4000                            # dev
enforce_ssl: prucia.pl
logo: logo.png                                        # Site logo
locale: en_US

# Menu visibility
menu:
  posts_visible: false
  resume_visible: true
  projects_visible: false
  cycling_visible: false

# Left Block Images
background:
  homepage: images/home.jpg                           # this image will be shown on homepage's left block
  post-list: images/post_list.jpg                     # this image will be shown on post list page
  project-list: images/project_list.jpg               # this image will be shown on project list page
  resume: images/resume.jpg                           # this image will be shown on skills page
  cycling: images/cycling.jpg                         # this image will be shown on cycling page
  default-post: images/default_post.jpg               # this image will be shown when post's front matter doesn't specify any image
  default-project: images/default_project.jpg         # this image will be shown when project's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed
collections:
  projects:
    output:         true
    permalink:      /:title/


# Analytics config
analytics:
  
  # Google Analytics
  google-analytics:
    tracking-id: UA-10401898-3

  # clicky.com
  clicky:
    tracking-id: 101013602

  track-social-links: true


# Social Links
email:              piotr@prucia.pl
#google-plus:       username
twitter:            pprucia
#facebook:          username
github:             pprucia
#stackoverflow:     123456/username   # from a "http://stackoverflow.com/users/123456/username" link
linkedin:           pprucia
#xing:              username
#instagram:         username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:             username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username
strava:             8814773            # custom svg icon for now, check font awesome for updates # number form a my profile link https://www.strava.com/athletes/123456
goodreads:          53513877           # number from https://www.goodreads.com/user/show/0123456789

# Other Links (drawn like social links)
#public-key:         filename.pgp       # name of the file placed in ./assets/public/

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-redirect-from

whitelist:
  - jekyll-feed
  - jekyll-redirect-from

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
